# Generated by Django 4.0.1 on 2022-01-26 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
